print("Aniaml Stroy Mad-Lib")
print("Instructions: The program will prompt for a type of word to enter. After all words are entered the program will print a story.")
place1 = input("Enter a location: ")
name1 = input("Enter a man's name: ")
animal1 = input("Enter an animal: ")
animalname1 = input("Enter a name for the animal: ")
vehicle1 = input("Enter a type of car: ")
adverb1 = input("Enter an adverb: ")
color1 = input("Enter a color: ")
tool1 = input("Enter a tool: ")
size1 = input("Enter a clothing size: ")
clothes1 = input("Enter an article of clothing: ")
verb1 = input("Enter a past tense vern someone can do to someone else, i.e. punched: ")
animal2 = input("Enter another animal: ")
adj1 = input("Enter an adjective: ")
noun1 = input("Enter your favorite band: ")
print(f"One day in {place1}, a man named {name1} was eating lunch when all of a sudden an agressive {animal1} named {animalname1} flew by and stole his food. The man {adverb1} got into his {vehicle1} and chased after {animalname1}. The man was catching up to {animalname1} when a {color1} {tool1} hit him on the head. He was just getting up when a {adj1} {animal2} in a {size1} {clothes1} {verb1} {animalname1}. The man went and thanked the {animal2} and went off to see {noun1}.The End.")

